# Generated by Django 6.0.3 on 2026-03-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveBigIntegerField(default=20),
            preserve_default=False,
        ),
    ]
